[tool.ruff]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.

[tool.ruff.lint]

fixable = ["I"]

ignore = [
    "E501", # line too long, handled by black
]

select = [
    "E", # pycodestyle errors
    "F", # pyflakes
    "I", # isort
]

mccabe = [10]

# Exclude a variety of commonly ignored directories.
exclude = [
    "*/tests.py",
    "*/migrations/*.py",
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "venv",
]

[tool.isort]
line_length = 88

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "backend.settings"
python_files = "tests.py test_*.py *_tests.py"
addopts = "--nomigrations --cov=. --cov-report=html --cov-report=term"

[tool.coverage.run]
omit = [
    "*/migrations/*",
    "*/tests/*",
    "tests.py",
    "asgi.py",
    "wsgi.py",
    "manage.py",
]

[tool.mypy]
mypy_path = "backend"
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]
ignore_missing_imports = true
strict = true
exclude = [
    "authentication/factories.py",
    "content/factories.py",
    "entities/factories.py",
    "events/factories.py",
]
enable_incomplete_feature = ["Unpack"]

[[tool.mypy.overrides]]
module = ["authentication.*", "content.*", "entities.*", "events.*"]
follow_imports = "skip"

[tool.django-stubs]
django_settings_module = "backend.settings"
